### PR TITLE
Improve failure handling in workspace::apply_edit

### PR DESCRIPTION
**Pull request by tadeokondrak**
It compiles, but I haven't tested it yet.

### CODE REVIEW

**Comment by tadeokondrak** [comment]
Not really sure how to check if it sends the right reply (since I don't know any language server other than rust-analyzer that does file operations, and it uses applySourceChange), but it still seems to work.

**Comment by ul** [comment]
@topisani would you mind testing it with clangd (iirc you use it actively)?

**Comment by topisani** [comment]
Yep, gimme just a few days, I'll try it out

**Comment by ul** [comment]
I guess we can merge and see how it works in the wild. I don't see any immediate problems with the code or after trying locally.

**Pull request merged**
