### PR TITLE
Reference AUR package

### PR DESCRIPTION
**Pull request by GordStephen**
I've created an AUR package to automate/structure installation for ArchLinux users here: https://aur.archlinux.org/packages/kak-lsp-git/ - this adds a reference to it in the README.

Regarding the package itself, happy to incorporate any suggestions / changes to the install process. You can see the PKGBUILD file [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kak-lsp-git).

### CODE REVIEW

**Comment by ul** [comment]
Thank you for contribution!

PKGBUILD looks fine to me, the only thing which might need to be fixed is [install -Dt "${pkgdir}/etc/" kak-lsp.toml](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kak-lsp-git#n33) — unfortunately at the moment kak-lsp doesn't try to read from that location and after installation it will be not immediately usable. User need to copy config manually into `~/.config/kak-lsp/`. I think it might be worth mention in package description and/or in installation message. I raised #44 to fix this problem (actually I will do it right now because it's easy to do and result should be quite beneficial)

**Comment by GordStephen** [comment]
Yeah, there's a post-install message about that (as well as activating the systemd unit) - https://aur.archlinux.org/cgit/aur.git/tree/kak-lsp-git.install?h=kak-lsp-git

**Comment by ul** [comment]
Ah, I missed it, thanks for pointing out correct place. Anyway, with the latest master copying file should be required only for customization (which I guess virtually everyone does because default config is far from being complete or universal).

**Comment by Foxboron** [comment]
@GordStephen Yo! Thanks for the AUR submission.

A few things to point out in the PKGBUILD:
-  The `v` from the version should be parsed out.  Mentioned in the [VCS package guidelines](https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git)
- The example you have put into `/etc/kak-lsp.toml` should be removed and placed into `/usr/share/$pkgname/examples/kak-lsp.toml`
- I also think you should be using `install -Dm644` and such when installing files.

**Comment by GordStephen** [comment]
Thanks for the feedback! I'll push a new release.

**Comment by GordStephen** [comment]
@Foxboron I [incorporated](https://aur.archlinux.org/cgit/aur.git/commit/?h=kak-lsp-git&id=d107590775937859750099ae5b68ae5571123433) those changes, if you have any other suggestions let me know.

**Comment by Foxboron** [comment]
They look great! Awesome work :)

**Pull request merged**
